# -*- coding: utf-8 -*-
"""Listadeexercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13pwvTDDipMjQxeeUIYOb3E7b_68kOoJE
"""

print ("Adição")

a = float (input("Digite um número;"))
b = float (input("Digite um número;"))
soma = float

soma = a + b

print ("O resultado da soma é:", soma)

print ("Subtração")

a = float (input("Digite um número;"))
b = float (input("Digite um número;"))
sub = float

sub = a - b

print ("O resultado da subtração é:", sub)

6

print ("Multiplicação")

a = int (input("Digite um número;"))
b = int (input("Digite um número;"))
multi = int

multi = a * b

print ("O resultado da multiplicação é:", multi)

print ("Antecessor e sucessor")

a = int (input("Digite um número;"))
sucessor = int
antecessor = int

sucessor = a + 1
antecessor = a -1

print ("Seu sucessor é:", sucessor)
print ("Seu antecessor é:", antecessor)

print ("dobro e triplo")

a = int (input("Digite um número;"))
dobro = int
triplo = int

dobro = a * 2
triplo = a * 3


print ("O dobro do número digitado é", dobro)
print("e o triplo é:", triplo)

print ("Area do triangulo")

a = float (input("Digite o valor da base;"))
b = float (input("Digite o valor da altura;"))
area = float

area = (a*b)/2

print ("A area do triangulo é:", area)

print ("Perimetro do retangulo")
b = int (input("Digite o valor da base;"))
h = int (input("Digite o valor da altura;"))
p = float

p = 2 * (b+h)

print ("O perimetro do retangulo é:", p)

print ("Impar ou par")

numero = int(input("Digite um numero:"))

if numero %2 == 0:
  print ("Seu numero é par")

else:
  print("Seu numero é impar")

print ("Negativo ou positivo")

numero = int (input("Digite um numero"))

if numero > 0:
  print("Seu numero é positivo")

elif numero < 0:
    print("Seu numero é negativo")


else:
  print("Seu numero é 0")

print("Qual dos três é maior?")

a = float(input("Escreva um numero:"))
b = float(input("Escreva um numero:"))
c = float(input("Escreva um numero:"))
maior = float

maior = a
if (b > maior):
  maior = b

if (c > maior):
  maior = c

print("O maior dos três é :", maior)

print ("Idade de votar")

idade = int(input("Escreva sua idade:"))
titulo = bool (input("Você tem titulo de eleitor?"))

if idade >=16 and titulo:
  Sim = True
  Não = False
  print("Você pode votar")

else:
 print ("Você não pode votar")

print("Quem pode dirigir")

print ("Desconto a vista 10%")